---
title: "Hierarchical Clustering, Parallel Coordinates, and Phyloseq"
author: "Kris Sankaran"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Hierarchical Clustering, Parallel Coordinates, and Phyloseq}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

This application is motivated by [http://statweb.stanford.edu/~susan/summer12/phyloseq-demosh.html](http://statweb.stanford.edu/~susan/summer12/phyloseq-demosh.html).

```{r setup}
library("treelapse")
library("phyloseq")
library("ape")
library("knitr")
opts_chunk$set(out.width = "700px", out.height = "600px", cache = FALSE)
data(GlobalPatterns)
gp_subset <- GlobalPatterns %>%
  filter_taxa(function(x) { var(x) > 9.22 * 1e5 }, prune = TRUE) %>%
  transform_sample_counts(asinh)
```

```{r, prep_data}
## Code from http://statweb.stanford.edu/~susan/summer12/phyloseq-demosh.html
GPUF <- UniFrac(gp_subset)
gp_hclust <- hclust(GPUF, method = "complete")

## extract edges from hierarchical clustering
edges <- as.phylo(gp_hclust)$edge
colnames(edges) <- c("parent", "child")
class(edges) <- "character"
sample_names_sub <- sample_names(gp_subset)
names(sample_names_sub) <- seq_len(nsamples(gp_subset))
rownames(edges) <- edges[, "child"]
edges[names(sample_names_sub), "child"] <- sample_names_sub

## Prepare aggregated values
X <- get_taxa(gp_subset)
taxa <- tax_table(gp_subset)
for (i in seq_len(nrow(taxa))) {
  taxa[i, ] <- na.locf(as.character(taxa[i, ]))
}
rownames(X) <- paste0("s", rownames(taxa))
plot_order <- dist(X) %>%
  hclust() %>%
  as.dendrogram() %>%
  order.dendrogram() 
X <- X[plot_order, ]

values <- tree_fun_multi(
  edges,
  X,
  tree_mean
)
values$time <- rownames(X)[values$row]

style_opts <- list(
  "x_axis_rotation" = 45,
  "axis_font_size" = 9,
  "axis_text_anchor" = "start",
  "margin" = list(
    "bottom" = 75
  )
)
timebox_tree(
  values,
  edges,
  style_opts = style_opts
)
```

```{r treebox}
treebox(
  values,
  edges,
  style_opts = style_opts
)
```
