---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, setup}
library("treelapse")
library("data.table")
library("jsonlite")

edgelist <- fread("../treelapse_expers/data/tax_el.csv")
values <- fread("../treelapse_expers/data/input_df.csv")
setnames(values, c("sample", "unit", "time", "value"))

library("devtools")
document()
install()
doi_tree(values, edgelist, "Bacteria", width = 2000, height = 700)
```

```{r, phyloseq}
library("phyloseq")
library("zoo")
data(GlobalPatterns)

GPr <- transform_sample_counts(GlobalPatterns, function(x) x / sum(x) )
GPfr <- filter_taxa(GPr, function(x) mean(x) > 1e-3, TRUE)
taxa <- taxa_edgelist(tax_table(GPfr))

values <- tree_counts(
  as.matrix(tax_tree$el),
  tax_tree$inv_mapping,
  log(1 + otu_table(bact)@.Data[, 1])
)
setnames(values, c("unit", "value"))

el <- tax_tree$el
el <- el[el$parent != el$child, ]
el$parent <- tax_tree$inv_mapping[el$parent]
el$child <- tax_tree$inv_mapping[el$child]
el <- el[!(el$child %in% tax[, "OTU"]), ]

doi_tree(values, el, "Bacteria", width = 50000, height = 500)
```
